-- Ruby Parker Supabase schema (already run during setup)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  is_admin boolean not null default false,
  membership_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  caption text not null default '',
  storage_path text,
  mime_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  provider text not null,
  reference text unique,
  amount integer not null,
  currency text not null default 'NGN',
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.btc_submissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  tx_hash text not null,
  amount_note text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.payments enable row level security;
alter table public.btc_submissions enable row level security;
