-- Ruby Parker Supabase schema (already run during setup)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  is_admin boolean not null default false,
  membership_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  caption text not null default '',
  storage_path text,
  mime_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  provider text not null,
  reference text unique,
  amount integer not null,
  currency text not null default 'USD',
  status text not null,
  transaction_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.btc_submissions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  tx_hash text not null,
  amount_note text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.payments add column if not exists transaction_id text;
alter table public.payments alter column currency set default 'USD';

alter table public.users enable row level security;
alter table public.posts enable row level security;
alter table public.payments enable row level security;
alter table public.btc_submissions enable row level security;

-- Community features
create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.post_likes enable row level security;
alter table public.comments enable row level security;

create index if not exists comments_post_id_idx on public.comments(post_id, created_at);
create index if not exists payments_user_id_idx on public.payments(user_id, created_at);
create index if not exists btc_submissions_user_id_idx on public.btc_submissions(user_id, created_at);
